{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.136.1202.0 (24.09)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"KPIs\",\"Correct Name\",\"RAG Order\"]"
      }
    ],
    "culture": "en-GB",
    "cultures": [
      {
        "name": "en-GB",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Correct Name",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"fZHPbsIwDMZfxeppE90L7DZN3aUSRc3QDoiDSV2IlDqoSTd4e5KS/tkGXKzo8+/7bMWbTSJcVxE70UlJ1iZpIuAFogiDuk0nEJ2yNUqnDAd6IGcyPC2FSEFkvqw++1pm4rlPeTfN8cu0uvLe8NbUO0p09AolWQemhisQ8A/FyFKhfvPJ3+RNo6LPcBXHbZdds6PWwjhond+ass4Hh40kTxuxU9zhw508FIP/wX+jvZmwlYeczY+mak/xfwcdFjC2IDvJA7JngjNj3GlqfFK0wEwJQHGkth+Nerpdced2M/hXcODnudsL\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Raw Name\" = _t, Name = _t]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Raw Name\", type text}, {\"Name\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "f73488bb-6aa3-4439-8d3c-05342f888e96"
      }
    ],
    "relationships": [
      {
        "name": "AutoDetected_07596d40-1feb-4320-a0d0-94c4f9c6bb32",
        "fromColumn": "RAG",
        "fromTable": "KPIs",
        "toColumn": "RAG",
        "toTable": "RAG Order"
      }
    ],
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "KPIs",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "68640a97-537e-47f4-a289-22b6e751ad45",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "KPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8882b8b-553f-413e-9f7f-1480db009bcb",
            "sourceColumn": "KPI",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5964ffbd-d561-432c-8f17-a5daa3d26c27",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Owner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4390a60-bfad-418e-b1d9-45040b880aff",
            "sourceColumn": "Owner",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b1d21bad-20bc-400d-989c-e9ac7f3e4a9c",
            "sourceColumn": "Value",
            "summarizeBy": "sum"
          },
          {
            "name": "Benchmark",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6684f18a-e0e2-4ebf-bb80-0ceccd1da44f",
            "sourceColumn": "Benchmark",
            "summarizeBy": "sum"
          },
          {
            "name": "Difference against benchmark",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f2265294-4e7e-4b8b-8ef4-7a582ab18b9c",
            "sourceColumn": "Difference against benchmark",
            "summarizeBy": "sum"
          },
          {
            "name": "RAG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "79653bc0-8ce5-4bf9-9be4-dd72111f3483",
            "sourceColumn": "RAG",
            "summarizeBy": "none"
          },
          {
            "name": "Last Update Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "49782ed3-42b6-4a06-af80-249fd6286934",
            "sourceColumn": "Last Update Date",
            "summarizeBy": "none"
          },
          {
            "name": "Reporting Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a24dcb18-d5b2-4b86-952d-b3db7a5391cd",
            "sourceColumn": "Reporting Period",
            "summarizeBy": "none"
          },
          {
            "name": "Notes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ef38ecc-8207-429e-bc49-9212d5afc677",
            "sourceColumn": "Notes",
            "summarizeBy": "none"
          },
          {
            "name": "RAG Logic",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "77e9ccc9-fed6-4d42-b8c9-dfc0d4504b75",
            "sourceColumn": "RAG Logic",
            "summarizeBy": "none"
          },
          {
            "name": "Value Format",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f35d99c2-1126-4d98-90ca-08cae505dd6a",
            "sourceColumn": "Value Format",
            "summarizeBy": "none"
          },
          {
            "name": "Difference Format",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a3d4ad0c-423a-4dc9-93a0-0ed0c637cfb4",
            "sourceColumn": "Difference Format",
            "summarizeBy": "none"
          },
          {
            "name": "Type of KPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15868af8-7397-4b73-a37c-d4d756bdf16f",
            "sourceColumn": "Type of KPI",
            "summarizeBy": "none"
          },
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "351c3582-0cd6-4c10-9f29-95b2d9a7b356",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "92d37e11-8dc9-457a-b202-6ba92dcb686b",
        "measures": [
          {
            "name": "Actual",
            "expression": "FORMAT(SELECTEDVALUE('KPIs'[Value]), SELECTEDVALUE('KPIs'[Value Format]))",
            "lineageTag": "724e8aa3-7ad7-49f3-9f17-db6851d5346b"
          },
          {
            "name": "Target",
            "expression": "FORMAT(SELECTEDVALUE('KPIs'[Benchmark]), SELECTEDVALUE('KPIs'[Value Format]))",
            "lineageTag": "ddcb0b88-1774-488d-8ec3-66beadd5a7ca"
          },
          {
            "name": "Difference",
            "expression": "FORMAT(SELECTEDVALUE('KPIs'[Difference against benchmark]), SELECTEDVALUE('KPIs'[Difference Format]))",
            "lineageTag": "43375a48-c2bb-4295-9187-d8eb37a0c1fa"
          },
          {
            "name": "KPI Colour",
            "expression": [
              "",
              "SWITCH(SELECTEDVALUE(KPIs[RAG]),",
              "\"R\", \"#ed1a37\",",
              "\"A\", \"#fdab05\",",
              "\"G\", \"#009383\")"
            ],
            "lineageTag": "5762f312-8d90-45d1-8dee-423b1e08fa52"
          },
          {
            "name": "_1 Tagline",
            "expression": [
              "",
              "\"<style>",
              "    p {",
              "        font-family: 'Segoe UI', serif;",
              "        font-size: 30px;",
              "        color: white;",
              "        background-color: transparent;",
              "        line-height: 115%;",
              "    }",
              "</style>",
              "<p>",
              "    Transforming <br>",
              "    Education <br>",
              "    Creating Futures",
              "</p>\"",
              ""
            ],
            "lineageTag": "3f5aa4f1-66b1-4b11-a0e8-6886b435f0c1"
          },
          {
            "name": "_1 Heading",
            "expression": [
              "",
              "\"<style>",
              "    p {",
              "        font-family: 'Segoe UI', serif;",
              "        font-size: 60px;",
              "        color: white;",
              "        background-color: transparent;",
              "        line-height: 115%;",
              "        font-weight: bold;",
              "    }",
              "</style>",
              "<p>",
              "    KPI Scorecard Dashboard",
              "</p>\"",
              ""
            ],
            "lineageTag": "00922753-aa5a-466c-9a51-d745f7eca08e"
          },
          {
            "name": "_1 Page Titles",
            "expression": [
              "",
              "\"<style>",
              "    p {",
              "        font-family: 'Segoe UI', serif;",
              "        font-size: 30px;",
              "        color: white;",
              "        background-color: transparent;",
              "        line-height: 115%;",
              "    }",
              "    .red-text {",
              "        color: white;",
              "        font-weight: bold;",
              "    }",
              "</style>",
              "<p>",
              "    <span class='red-text'>Pages</span> <br>",
              "     Strategic KPIs<br>",
              "     Operational KPIs",
              "</p>\"",
              ""
            ],
            "lineageTag": "3ab53b29-bdb7-4908-b52c-942e7f0639df"
          },
          {
            "name": "Percentage Value",
            "expression": [
              "",
              "SUM(KPIs[Value])"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "6efb08c4-2a04-4299-a729-57b02494ac97"
          },
          {
            "name": "Percentage Target",
            "expression": [
              "",
              "SUM(KPIs[Benchmark])"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "803b7984-65c2-4ff0-9793-e9fabff12129"
          },
          {
            "name": "Number Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "SUM(KPIs[Value])"
            ],
            "lineageTag": "68145570-4dd0-4558-b13a-f638f2cd5b94"
          },
          {
            "name": "Number Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "SUM(KPIs[Benchmark])"
            ],
            "lineageTag": "0debc2f1-c7a4-40f9-a6e6-ae7d25408f49"
          },
          {
            "name": "Money Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-GB\"}"
              }
            ],
            "expression": [
              "",
              "SUM(KPIs[Benchmark])"
            ],
            "formatString": "\"\"#,0.00;-\"\"#,0.00;\"\"#,0.00",
            "lineageTag": "71d89da4-c19c-42ef-959e-3436f287751c"
          },
          {
            "name": "Money Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-GB\"}"
              }
            ],
            "expression": [
              "",
              "SUM(KPIs[Value])"
            ],
            "formatString": "\"\"#,0.00;-\"\"#,0.00;\"\"#,0.00",
            "lineageTag": "4f93ec1c-5752-4f73-b056-dcb513961f94"
          }
        ],
        "partitions": [
          {
            "name": "KPIs",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = SharePoint.Files(\"https://uolonline.sharepoint.com/sites/uliamiteam/\", [ApiVersion = 15]),",
                "    #\"Sorted Rows\" = Table.Sort(Source,{{\"Date created\", Order.Descending}}),",
                "    #\"Strategic and Operational KPIs Data back-end new version August 24 xlsx_https://uolonline sharepoint com/sites/uliamiteam/Documents NEW/New Structure/PowerBI Dashboards/Our Dashboards/KPI Reporting/\" = #\"Sorted Rows\"{[Name=\"Strategic and Operational KPIs Data back-end new version August 24.xlsx\",#\"Folder Path\"=\"https://uolonline.sharepoint.com/sites/uliamiteam/Documents NEW/New Structure/PowerBI Dashboards/Our Dashboards/KPI Reporting/\"]}[Content],",
                "    #\"Imported Excel Workbook\" = Excel.Workbook(#\"Strategic and Operational KPIs Data back-end new version August 24 xlsx_https://uolonline sharepoint com/sites/uliamiteam/Documents NEW/New Structure/PowerBI Dashboards/Our Dashboards/KPI Reporting/\"),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Imported Excel Workbook\", each ([Kind] = \"Table\")),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"Kind\", \"Hidden\", \"Item\"}),",
                "    #\"Expanded Data\" = Table.ExpandTableColumn(#\"Removed Columns\", \"Data\", {\"ID\", \"KPI\", \"Category\", \"Owner\", \"Value\", \"Benchmark\", \"Value Format\", \"Difference against benchmark\", \"Difference Format\", \"RAG\", \"RAG Logic\", \"Last Update Date\", \"Reporting Period\", \"Notes\"}, {\"ID\", \"KPI\", \"Category\", \"Owner\", \"Value\", \"Benchmark\", \"Value Format\", \"Difference against benchmark\", \"Difference Format\", \"RAG\", \"RAG Logic\", \"Last Update Date\", \"Reporting Period\", \"Notes\"}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Expanded Data\", {\"Name\"}, #\"Correct Name\", {\"Raw Name\"}, \"Correct Name\", JoinKind.LeftOuter),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Merged Queries\",{\"Name\"}),",
                "    #\"Expanded Correct Name\" = Table.ExpandTableColumn(#\"Removed Columns2\", \"Correct Name\", {\"Name\"}, {\"Name\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Correct Name\",{{\"Benchmark\", type number}, {\"Value\", type number}, {\"Difference against benchmark\", type number}, {\"Last Update Date\", type date}, {\"Reporting Period\", type text}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type\", \"Type of KPI\", each if Text.StartsWith([Name], \"O -\") then \"Operational\" else \"Strategic\", type text),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"ID\", Int64.Type}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "RAG Order",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "RAG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "35fd7519-af8c-4337-9b92-633ff53e85a1",
            "sortByColumn": "Index",
            "sourceColumn": "RAG",
            "summarizeBy": "none"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf8b251c-dea4-439f-968a-19bad22566d5",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1ea99cde-3cb0-4be8-92c3-6a597cd612bd",
        "partitions": [
          {
            "name": "RAG Order",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WclfSUTJUitWJVnIEsozArCAgy1gpNhYA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [RAG = _t, Index = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"RAG\", type text}, {\"Index\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}